/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardHostelIndexRouteImport } from './routes/dashboard/hostel/index'
import { Route as DashboardUsersStaffRouteImport } from './routes/dashboard/users/staff'
import { Route as DashboardUsersAllRouteImport } from './routes/dashboard/users/all'
import { Route as DashboardUsersAccessRouteImport } from './routes/dashboard/users/access'
import { Route as DashboardHostelRoomsRouteImport } from './routes/dashboard/hostel/rooms'
import { Route as DashboardHostelResidentsRouteImport } from './routes/dashboard/hostel/residents'
import { Route as DashboardHostelComplaintsRouteImport } from './routes/dashboard/hostel/complaints'
import { Route as DashboardHostelAllocationsRouteImport } from './routes/dashboard/hostel/allocations'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHostelIndexRoute = DashboardHostelIndexRouteImport.update({
  id: '/hostel/',
  path: '/hostel/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersStaffRoute = DashboardUsersStaffRouteImport.update({
  id: '/users/staff',
  path: '/users/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersAllRoute = DashboardUsersAllRouteImport.update({
  id: '/users/all',
  path: '/users/all',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersAccessRoute = DashboardUsersAccessRouteImport.update({
  id: '/users/access',
  path: '/users/access',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHostelRoomsRoute = DashboardHostelRoomsRouteImport.update({
  id: '/hostel/rooms',
  path: '/hostel/rooms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHostelResidentsRoute =
  DashboardHostelResidentsRouteImport.update({
    id: '/hostel/residents',
    path: '/hostel/residents',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardHostelComplaintsRoute =
  DashboardHostelComplaintsRouteImport.update({
    id: '/hostel/complaints',
    path: '/hostel/complaints',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardHostelAllocationsRoute =
  DashboardHostelAllocationsRouteImport.update({
    id: '/hostel/allocations',
    path: '/hostel/allocations',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/hostel/allocations': typeof DashboardHostelAllocationsRoute
  '/dashboard/hostel/complaints': typeof DashboardHostelComplaintsRoute
  '/dashboard/hostel/residents': typeof DashboardHostelResidentsRoute
  '/dashboard/hostel/rooms': typeof DashboardHostelRoomsRoute
  '/dashboard/users/access': typeof DashboardUsersAccessRoute
  '/dashboard/users/all': typeof DashboardUsersAllRoute
  '/dashboard/users/staff': typeof DashboardUsersStaffRoute
  '/dashboard/hostel/': typeof DashboardHostelIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/hostel/allocations': typeof DashboardHostelAllocationsRoute
  '/dashboard/hostel/complaints': typeof DashboardHostelComplaintsRoute
  '/dashboard/hostel/residents': typeof DashboardHostelResidentsRoute
  '/dashboard/hostel/rooms': typeof DashboardHostelRoomsRoute
  '/dashboard/users/access': typeof DashboardUsersAccessRoute
  '/dashboard/users/all': typeof DashboardUsersAllRoute
  '/dashboard/users/staff': typeof DashboardUsersStaffRoute
  '/dashboard/hostel': typeof DashboardHostelIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/hostel/allocations': typeof DashboardHostelAllocationsRoute
  '/dashboard/hostel/complaints': typeof DashboardHostelComplaintsRoute
  '/dashboard/hostel/residents': typeof DashboardHostelResidentsRoute
  '/dashboard/hostel/rooms': typeof DashboardHostelRoomsRoute
  '/dashboard/users/access': typeof DashboardUsersAccessRoute
  '/dashboard/users/all': typeof DashboardUsersAllRoute
  '/dashboard/users/staff': typeof DashboardUsersStaffRoute
  '/dashboard/hostel/': typeof DashboardHostelIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/hostel/allocations'
    | '/dashboard/hostel/complaints'
    | '/dashboard/hostel/residents'
    | '/dashboard/hostel/rooms'
    | '/dashboard/users/access'
    | '/dashboard/users/all'
    | '/dashboard/users/staff'
    | '/dashboard/hostel/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/hostel/allocations'
    | '/dashboard/hostel/complaints'
    | '/dashboard/hostel/residents'
    | '/dashboard/hostel/rooms'
    | '/dashboard/users/access'
    | '/dashboard/users/all'
    | '/dashboard/users/staff'
    | '/dashboard/hostel'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/hostel/allocations'
    | '/dashboard/hostel/complaints'
    | '/dashboard/hostel/residents'
    | '/dashboard/hostel/rooms'
    | '/dashboard/users/access'
    | '/dashboard/users/all'
    | '/dashboard/users/staff'
    | '/dashboard/hostel/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hostel/': {
      id: '/dashboard/hostel/'
      path: '/hostel'
      fullPath: '/dashboard/hostel/'
      preLoaderRoute: typeof DashboardHostelIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/staff': {
      id: '/dashboard/users/staff'
      path: '/users/staff'
      fullPath: '/dashboard/users/staff'
      preLoaderRoute: typeof DashboardUsersStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/all': {
      id: '/dashboard/users/all'
      path: '/users/all'
      fullPath: '/dashboard/users/all'
      preLoaderRoute: typeof DashboardUsersAllRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/access': {
      id: '/dashboard/users/access'
      path: '/users/access'
      fullPath: '/dashboard/users/access'
      preLoaderRoute: typeof DashboardUsersAccessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hostel/rooms': {
      id: '/dashboard/hostel/rooms'
      path: '/hostel/rooms'
      fullPath: '/dashboard/hostel/rooms'
      preLoaderRoute: typeof DashboardHostelRoomsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hostel/residents': {
      id: '/dashboard/hostel/residents'
      path: '/hostel/residents'
      fullPath: '/dashboard/hostel/residents'
      preLoaderRoute: typeof DashboardHostelResidentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hostel/complaints': {
      id: '/dashboard/hostel/complaints'
      path: '/hostel/complaints'
      fullPath: '/dashboard/hostel/complaints'
      preLoaderRoute: typeof DashboardHostelComplaintsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hostel/allocations': {
      id: '/dashboard/hostel/allocations'
      path: '/hostel/allocations'
      fullPath: '/dashboard/hostel/allocations'
      preLoaderRoute: typeof DashboardHostelAllocationsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardHostelAllocationsRoute: typeof DashboardHostelAllocationsRoute
  DashboardHostelComplaintsRoute: typeof DashboardHostelComplaintsRoute
  DashboardHostelResidentsRoute: typeof DashboardHostelResidentsRoute
  DashboardHostelRoomsRoute: typeof DashboardHostelRoomsRoute
  DashboardUsersAccessRoute: typeof DashboardUsersAccessRoute
  DashboardUsersAllRoute: typeof DashboardUsersAllRoute
  DashboardUsersStaffRoute: typeof DashboardUsersStaffRoute
  DashboardHostelIndexRoute: typeof DashboardHostelIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardHostelAllocationsRoute: DashboardHostelAllocationsRoute,
  DashboardHostelComplaintsRoute: DashboardHostelComplaintsRoute,
  DashboardHostelResidentsRoute: DashboardHostelResidentsRoute,
  DashboardHostelRoomsRoute: DashboardHostelRoomsRoute,
  DashboardUsersAccessRoute: DashboardUsersAccessRoute,
  DashboardUsersAllRoute: DashboardUsersAllRoute,
  DashboardUsersStaffRoute: DashboardUsersStaffRoute,
  DashboardHostelIndexRoute: DashboardHostelIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
